# Attogram Filesystem-Cache - https://github.com/attogram/filesystem-cache
# Travis CI - https://travis-ci.org/attogram/filesystem-cache
language: php
php:
#  - '7.0'
#  - '7.1'
#  - '7.2'
  - '7.3'
  - '7.4'
  - nightly
matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
before_script:
  - composer install
script:
  - if find src/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find tests/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find vendor/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - phpunit
